local ops = {}

ops._index = ops
ops['#'] = include("orca/lib/library/_comment")
ops['='] = include("orca/lib/library/_osc_out")
ops['*'] = include("orca/lib/library/_bang")
ops["'"] = include("orca/lib/library/_timber")
ops[':'] = include("orca/lib/library/_midi_out")
ops['/'] = include("orca/lib/library/_softcut_op")
ops['\\'] = include("orca/lib/library/_rnote")
ops.A = include("orca/lib/library/a")
ops.B = include("orca/lib/library/b")
ops.C = include("orca/lib/library/c")
ops.D = include("orca/lib/library/d")
ops.E = include("orca/lib/library/e")
ops.F = include("orca/lib/library/f")
ops.G = include("orca/lib/library/g")
ops.H = include("orca/lib/library/h")
ops.I = include("orca/lib/library/i")
ops.J = include("orca/lib/library/j")
ops.K = include("orca/lib/library/k")
ops.L = include("orca/lib/library/l")
ops.M = include("orca/lib/library/m")
ops.N = include("orca/lib/library/n")
ops.O = include("orca/lib/library/o")
ops.P = include("orca/lib/library/p")
ops.Q = include("orca/lib/library/q")
ops.R = include("orca/lib/library/r")
ops.S = include("orca/lib/library/s")
ops.T = include("orca/lib/library/t")
ops.U = include("orca/lib/library/u")
ops.V = include("orca/lib/library/v")
ops.W = include("orca/lib/library/w")
ops.X = include("orca/lib/library/x")
ops.Y = include("orca/lib/library/y")
ops.Z = include("orca/lib/library/z")

return ops
